version: "3"

services:
  app:
    env_file:
      - .env
    image: sgcc_updater
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: sgcc_electricity
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    restart: unless-stopped
    volumes:
      - ./scripts:/app
    command: python3 main.py
    network_mode: "host"